/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.transporteshirata.GUI;

import javax.swing.JFrame;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("     \n     Principal     \n     ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        bt_conductor = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        openMenuItem1 = new javax.swing.JMenuItem();
        openMenuItem2 = new javax.swing.JMenuItem();
        bt_conductor1 = new javax.swing.JMenu();
        bt_mantenimiento = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        openMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_conductor.setMnemonic('f');
        bt_conductor.setText("Registro");
        bt_conductor.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Registrar camion");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        bt_conductor.add(openMenuItem);

        openMenuItem1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem1.setMnemonic('o');
        openMenuItem1.setText("Registrar conductor");
        openMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem1ActionPerformed(evt);
            }
        });
        bt_conductor.add(openMenuItem1);

        openMenuItem2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem2.setText("Volver");
        openMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem2ActionPerformed(evt);
            }
        });
        bt_conductor.add(openMenuItem2);

        menuBar.add(bt_conductor);

        bt_conductor1.setMnemonic('f');
        bt_conductor1.setText("Mantenimiento");
        bt_conductor1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N

        bt_mantenimiento.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bt_mantenimiento.setMnemonic('o');
        bt_mantenimiento.setText("Hacer mantenimiento");
        bt_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mantenimientoActionPerformed(evt);
            }
        });
        bt_conductor1.add(bt_mantenimiento);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItem1.setText("Historial Mantenimiento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        bt_conductor1.add(jMenuItem1);

        openMenuItem3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem3.setText("Volver");
        openMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem3ActionPerformed(evt);
            }
        });
        bt_conductor1.add(openMenuItem3);

        menuBar.add(bt_conductor1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        GuiRegistrarCamion v = new GuiRegistrarCamion();
        desktopPane.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void openMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem1ActionPerformed
        GuiRegistrarConductor c = new GuiRegistrarConductor();
        desktopPane.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_openMenuItem1ActionPerformed

    private void bt_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mantenimientoActionPerformed
        GuiMantenimiento m = new GuiMantenimiento();
        desktopPane.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_bt_mantenimientoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GuiHistorialMantenimiento hist = new GuiHistorialMantenimiento();
        desktopPane.add(hist);
        hist.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            this.setVisible(false);
            GuiLoginPrincipal p = new GuiLoginPrincipal();
            p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem2ActionPerformed
            this.setVisible(false);
            GuiLoginPrincipal p = new GuiLoginPrincipal();
            p.setVisible(true);
    }//GEN-LAST:event_openMenuItem2ActionPerformed

    private void openMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem3ActionPerformed
            this.setVisible(false);
            GuiLoginPrincipal p = new GuiLoginPrincipal();
            p.setVisible(true);      
    }//GEN-LAST:event_openMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bt_conductor;
    private javax.swing.JMenu bt_conductor1;
    private javax.swing.JMenuItem bt_mantenimiento;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem openMenuItem2;
    private javax.swing.JMenuItem openMenuItem3;
    // End of variables declaration//GEN-END:variables

}
